---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-deployment
  labels:
    type: proxy
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy1
  template:
    metadata:
      name: nginx-pod
      labels:
       type: proxy1
    spec:
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
           - containerPort: 80
...




