---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-nginx-deployment
  labels:
    type: proxy
    author: intelliqit
spec:
  replicas: 1
  selector:
    matchLabels:
      type: proxy2
  template:
    metadata:
      name: nginx-pod
      labels:
       type: proxy2
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
           - containerPort: 80
...




