---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: intelliqit
spec:
  type: NodePort
  ports:
   - targetPort: 8080
     port: 8080
     nodePort: 30008
  selector:
   author: intelliqit
   type: ci-cd
...
