---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
   author: intelliqit
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30010
  selector:
    
    type: proxy
...
