---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: intelliqit
spec:
  containers:
    - name: mydb
      image: mysql:8
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "2Gi" 
     volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: intelliqit
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: new-pvc
...
