---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
    author: intelliqit
spec:
  containers:
    - name: my-nginx
      image: nginx
      volumeMounts:
        - name: new-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: new-volume
      persistentVolumeClaim:
        claimName: my-pvc
...

